---
groups:
- name: build-pipeline
  jobs:
  - maven-build
  - deploy-to-dev
  - run-health-check
  - run-functional-check
  - deploy-to-staging
  # - run-e2e-test
  # - validate-test-result
  - deploy-to-production
  - promote-new-version
  # - upload-git-release

- name: init-dynatrace
  jobs: 
  - init-dynatrace-carts

- name: performance
  jobs:
  - run-performance-check
  - validate-performance-check

resource_types:
- name: dynatrace-resource
  type: docker-image
  source:
    repository: mvilliger/dynatrace-resource

resources:

#GitHub Release Repository
#- name: carts-release
#  type: github-release
#  source:
#    owner: acm-workshop-concourse
#    repository: carts
#    access_token: ((github-access-token))

# GitHub Repositories
- name: git-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/sockshop.git

- name: git-carts
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/carts.git

- name: dynatrace
  type: dynatrace-resource
  source:
    apitoken: ((dt_api_token))
    tenanthost: ((dt_tenant_url))

- name: carts-release-bucket
  type: s3
  source:
    region_name: eu-west-1
    regexp: carts/carts-(.*).jar
    bucket: ((s3-bucket))
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/((workshop-repository))/carts.git
    branch: master
    file: version

# - name: jmeter-test-image
#   type: docker-image
#   source:
#     repository: ((docker-hub-repository))/jmeter-test
#     username: ((docker-hub-username))
#     password: ((docker-hub-password))

# PCF Environments

- name: pcf-dev
  type: cf
  source:
    api: ((pcf-dev-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-dev-organization))
    space: ((pcf-dev-space))
    skip_cert_check: false

- name: pcf-staging
  type: cf
  source:
    api: ((pcf-staging-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-staging-organization))
    space: ((pcf-staging-space))
    skip_cert_check: false

- name: pcf-production
  type: cf
  source:
    api: ((pcf-production-api))
    username: ((pcf-username))
    password: ((pcf-password))
    organization: ((pcf-production-organization))
    space: ((pcf-production-space))
    skip_cert_check: false

jobs:

# Initialize Dynatrace Custom Device

- name: init-dynatrace-carts
  public: true
  plan:
  - aggregate: 
    - get: git-pipeline
    - get: git-carts
  - task: init-dynatrace-task
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/init-dynatrace-task.yml
    params: 
      apitoken: ((dt_api_token))
      tenanthost: ((dt_tenant_url))
      APP_REPO: git-carts

# Build jMeter Test Image

# - name: build-jmeter-test-image
#   serial: true
#   public: true
#   plan:
#   - get: git-carts
#     trigger: false
#   - put: jmeter-test-image
#     params:
#       build: git-carts/test
#       cache_tag: latest

# CARTS

- name: maven-build
  plan:
  - get: git-carts
    trigger: true
  - get: version
    params: { pre: build }
  - task: mvn-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven, tag: 3.2-jdk-8}
      inputs:
      - name: git-carts
      - name: version
      outputs:
      - name: workspace
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          # Caching Maven
          export ROOT_FOLDER=$( pwd )
          M2_HOME="${HOME}/.m2"
          M2_CACHE="${ROOT_FOLDER}/maven"
          echo "Generating symbolic link for Maven cache"
          ln -s "${M2_CACHE}" "${M2_HOME}"

          # Build App
          output_dir=workspace
          cd git-carts
          mvn -DskipTests package
          cd ..
          mv git-carts/target/carts.jar git-carts/target/carts-$(cat version/number).jar
          cp git-carts/target/carts-*.jar "${output_dir}/"
      caches:
        - path: maven
  - put: carts-release-bucket
    params:
      file: workspace/carts-*.jar

- name: deploy-to-dev
  serial: true
  public: true
  plan:
  - get: git-carts
    trigger: true
    passed:
      - maven-build
  - get: carts-release-bucket
    passed:
      - maven-build
  - get: git-pipeline
    trigger: false      
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      STAGE: Dev
      PCF_APP_SUFFIX: ((pcf-dev-carts-suffix)) 
      APP_REPO: git-carts
  - put: pcf-dev
    params:
      path: carts-release-bucket/carts-*.jar
      manifest: app-manifest-output/manifest.yml    
  - put: dynatrace
    params:
      monspecserviceenvironment: carts/Dev
      pipelinetaskname: deploy-to-dev
      deployversion: v1.0
      APP_REPO: git-carts

- name: run-health-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-carts
      trigger: true
      passed:
        - deploy-to-dev
    - get: git-pipeline
      trigger: false 
  - task: run-health-check
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/jmeter-test.yml
    params:
      APP_REPO: git-carts
      PRODUCTION: false
      SCRIPT_NAME: jmeter/basiccheck.jmx
      RESULT_DIR: HealthCheck
      PCF_APP_SUFFIX: ((pcf-dev-carts-suffix))
      PCF_APP_DOMAIN: ((pcf-dev-app-domain))
      CHECK_PATH: /health
      SERVER_PORT: 80
      VU_COUNT: 1
      LOOP_COUNT: 1
      DT_LTN: HealthCheck
      FUNC_VALIDATION: true
      THINK_TIME: 0

- name: run-functional-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-carts
      trigger: true
      passed:
        - run-health-check
    - get: git-pipeline
  - task: run-functional-check
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/jmeter-test.yml
    params:
      APP_REPO: git-carts
      PRODUCTION: false
      SCRIPT_NAME: jmeter/carts_load.jmx
      RESULT_DIR: FuncCheck
      PCF_APP_SUFFIX: ((pcf-dev-carts-suffix))
      PCF_APP_DOMAIN: ((pcf-dev-app-domain))
      CHECK_PATH: /health
      SERVER_PORT: 80
      VU_COUNT: 1
      LOOP_COUNT: 1
      DT_LTN: FuncCheck
      FUNC_VALIDATION: true
      AVG_RT_VALIDATION: 3000
      THINK_TIME: 0
          
- name: deploy-to-staging
  serial: true
  public: true
  plan:
  - get: git-carts
    trigger: true
    passed:
      - run-functional-check
  - get: carts-release-bucket
    passed:
      - maven-build
  - get: git-pipeline
    trigger: false      
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      STAGE: Staging
      PCF_APP_SUFFIX: ((pcf-staging-carts-suffix)) 
      APP_REPO: git-carts
  - put: pcf-staging
    params:
      path: carts-release-bucket/carts-*.jar
      manifest: app-manifest-output/manifest.yml             
  - put: dynatrace
    params:
      monspecserviceenvironment: carts/Staging
      pipelinetaskname: deploy-to-staging
      deployversion: v1.0 
      APP_REPO: git-carts 

# - name: run-e2e-test
#   serial: true
#   public: true
#   plan:
#   - aggregate:
#     - get: git-carts
#       trigger: true
#       passed:
#        - deploy-to-staging
#     - get: git-pipeline
#   - task: run-e2e-check
#     file: git-pipeline/deploy/cloud-foundry/ci/tasks/load-tests.yml
#     params:
#       APP_REPO: git-pipeline
#       FUNC_VALIDATION: yes
#       PRODUCTION: true
#       SCRIPT_NAME: deploy/cloud-foundry/ci/jmeterfront-end_e2e_load.jmx
#       PCF_APP_SUFFIX: ((pcf-staging-carts-suffix))
#       PCF_APP_DOMAIN: ((pcf-staging-app-domain))
#       DT_LTN: e2eCheck
#       VUCount: 5
#       LoopCount: 20 
#   - task: push-dynatrace-monspec-data
#     file: git-pipeline/deploy/cloud-foundry/ci/tasks/push-dynatrace-monspec-data.yml
#     params: 
#       monspecserviceenvironment: carts/Production-$NEXT_APP_COLOR
#       apitoken: ((dt_api_token))
#       tenanthost: ((dt_tenant_url))
#       APP_REPO: git-carts  

# - name: validate-e2e-check
#   serial: true
#   public: true
#   plan:
#   - get: git-carts
#     trigger: true
#     passed:
#       - run-e2e-test
#   - get: git-pipeline
#     trigger: false      
#   - task: get-current-app-color
#     file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
#     params:
#       PCF_APP_SUFFIX: ((pcf-production-carts-suffix))
#       PCF_API: ((pcf-production-api))
#       PCF_ORG: ((pcf-production-organization))
#       PCF_SPACE: ((pcf-production-space))    
#       PCF_USER: ((pcf-username))
#       PCF_PWD: ((pcf-password))
#   - task: validate-via-monspec
#     file: git-pipeline/deploy/cloud-foundry/ci/tasks/validate-via-monspec.yml
#     params: 
#       monspeccomparison: carts/Production-$NEXT_APP_COLOR\ToProduction-$CURRENT_APP_COLOR\Last5m
#       apitoken: ((dt_api_token))
#       tenanthost: ((dt_tenant_url))
#       APP_REPO: git-carts   

- name: deploy-to-production
  serial: true
  public: true
  plan:
  - get: git-carts
    trigger: true
    passed:
      - deploy-to-staging
  - get: carts-release-bucket
    passed:
      - maven-build
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-production-carts-suffix))
      PCF_API: ((pcf-production-api))
      PCF_ORG: ((pcf-production-organization))
      PCF_SPACE: ((pcf-production-space))  
      PCF_USER: ((pcf-username))
      PCF_PWD: ((pcf-password))
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      STAGE: Production 
      PCF_APP_SUFFIX: ((pcf-production-carts-suffix)) 
      APP_REPO: git-carts                
  - put: pcf-production
    params:
      path: carts-release-bucket/carts-*.jar
      manifest: app-manifest-output/manifest.yml
  - put: dynatrace
    params:
      monspecserviceenvironment: carts/Production
      pipelinetaskname: deploy-to-production
      deployversion: v1.0 
      APP_REPO: git-carts 

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: git-carts
    trigger: true
    passed:
      - deploy-to-production
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-production-carts-suffix))
      PCF_API: ((pcf-production-api))
      PCF_ORG: ((pcf-production-organization))
      PCF_SPACE: ((pcf-production-space))  
      PCF_USER: ((pcf-username))
      PCF_PWD: ((pcf-password))
  - task: switch-app-routes
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/update-routes.yml
    params:
      PCF_APP_SUFFIX: ((pcf-production-carts-suffix))
      PCF_APP_DOMAIN: ((pcf-production-app-domain))
      PCF_API: ((pcf-production-api))
      PCF_ORG: ((pcf-production-organization))
      PCF_SPACE: ((pcf-production-space))
      PCF_USER: ((pcf-username))
      PCF_PWD: ((pcf-password))

#- name: upload-carts-git-release
#  public: true
#  plan:
#  - aggregate:
#    - get: git-carts
#      trigger: true
#      passed: 
#        - promote-new-version-carts
#    - get: carts-release-bucket
#    - get: git-pipeline
#    - get: version
#      params: { pre: build }
#  - task: create-carts-release-info
#    file: git-pipeline/deploy/cloud-foundry/ci/tasks/prepare-release.yml
#    params:
#      APP_NAME: carts
#  - put: carts-release
#    params:
#      name: prepared-release/name
#      tag: prepared-release/tag
#      globs:
#      - carts-release-bucket/carts-*.jar
#  - put: version
#    params: { file: version/number }

- name: run-performance-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-carts
      trigger: false
    - get: git-pipeline
  - task: run-performance-check
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/jmeter-test.yml
    params:
      APP_REPO: git-carts
      PRODUCTION: false
      SCRIPT_NAME: jmeter/carts_load.jmx
      RESULT_DIR: PerfCheck
      PCF_APP_SUFFIX: ((pcf-dev-carts-suffix))
      PCF_APP_DOMAIN: ((pcf-dev-app-domain))
      SERVER_PORT: 80
      VU_COUNT: 10
      LOOP_COUNT: 250
      DT_LTN: FuncCheck
      FUNC_VALIDATION: false
      AVG_RT_VALIDATION: 3000
      THINK_TIME: 0
  - task: push-dynatrace-monspec-data
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/push-dynatrace-monspec-data.yml
    params: 
      monspecserviceenvironment: carts/Dev
      apitoken: ((dt_api_token))
      tenanthost: ((dt_tenant_url))
      APP_REPO: git-carts 

- name: validate-performance-check
  serial: true
  public: true
  plan:
  - get: git-carts
    trigger: true
    passed:
      - run-performance-check
  - get: git-pipeline
    trigger: false      
  - task: validate-via-monspec
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/validate-via-monspec.yml
    params: 
      monspeccomparison: carts/DevToDevLastHour
      apitoken: ((dt_api_token))
      tenanthost: ((dt_tenant_url))
      APP_REPO: git-carts 